# starts a mysql DB instance inside container, creates schema and populates seed data from ./sql/init.sql
# Docker runtime should be running `docker compose up`
version: '3.3'
services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
            - ./sql:/tmp/sql
        command: mysqld --init-file="/tmp/sql/init.sql"
# Names our volume
volumes:
    my-db: